import {test,expect} from '@playwright/test';
import {build} from 'esbuild';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
test('AGT-01 AGT-02 AGT-03 actual broker composition and persistent IndexedDB write admission',async({page})=>{
  const built=await build({entryPoints:['tests/fixtures/agent-host.ts'],bundle:true,format:'esm',platform:'browser',target:'es2022',write:false});const bytes=built.outputFiles[0]?.contents;if(!bytes)throw new Error('Missing agent test host');
  const server=createServer(async(req,res)=>{try{res.setHeader('cache-control','no-store');res.setHeader('x-content-type-options','nosniff');if(req.method!=='GET'){res.writeHead(405);res.end();return;}if(req.url==='/'){res.setHeader('content-type','text/html');res.end('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Scoped composition fixture</title><button id="run">Run scoped composition</button><output id="status"></output><script type="module" src="/host.js"></script></html>');return;}if(req.url==='/host.js'){res.setHeader('content-type','text/javascript');res.end(bytes);return;}if(req.url==='/fixtures/trust.json'){res.setHeader('content-type','application/json');res.end(await readFile('artifacts/packages/trust.json'));return;}const match=/^\/fixtures\/(notebook|canvas-board)\/(archive\.zip|envelope\.json|receipt\.json|receipt\.sig|envelope\.sig)$/.exec(req.url??'');if(match){res.setHeader('content-type',match[2]?.endsWith('.json')?'application/json':'application/octet-stream');res.end(await readFile(`artifacts/packages/${match[1]}/${match[2]}`));return;}res.writeHead(404);res.end();}catch{res.writeHead(503);res.end('Required fixture build unavailable');}});
  try{await new Promise<void>((ready,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',ready);});const address=server.address();if(!address||typeof address==='string')throw new Error('Missing agent fixture port');await page.goto(`http://127.0.0.1:${address.port}`);await page.getByRole('button',{name:'Run scoped composition'}).click();await expect(page.locator('#status')).toHaveText('PASS: actual approved selected binding, denied escalation/write, confirmed Canvas storage write, IndexedDB reopen and recreated-runner replay denial');}finally{if(server.listening)await new Promise<void>((done,reject)=>server.close(error=>error?reject(error):done()));}
});
