import {test,expect} from '@playwright/test';
test('RPC-01 RPC-02 hostile forged identity oversized requests and replay close real ports',async({page})=>{
 await page.goto('/spikes/hostile.html');
 for(const [button,writes]of [['Forge principal',0],['Replay request',1],['Oversized packet',0]] as const){await page.getByRole('button',{name:'Mount hostile fixture'}).click();const frame=page.frameLocator('#frame iframe');await expect(frame.getByRole('heading')).toHaveText('Hostile protocol fixture');await frame.getByRole('button',{name:button}).click();await expect(page.locator('#frame iframe')).toHaveCount(0);await expect(page.locator('#status')).toHaveText(`Revoked; writes=${writes}`);}
});
test('RPC-01 copied bootstrap from wrong window and retired actual channel cannot gain authority',async({page})=>{
 await page.goto('/spikes/hostile.html');await page.getByRole('button',{name:'Mount copied bootstrap fixture'}).click();const frame=page.frameLocator('#frame iframe');await expect(frame.getByRole('heading')).toHaveText('Hostile protocol fixture');await expect(page.locator('#attack-status')).toHaveText('Wrong-window attempted first; no transferred authority');await frame.getByRole('button',{name:'Retain actual port'}).click();await expect(page.locator('#attack-status')).toHaveText('Actual plugin port retained for revocation test');await page.getByRole('button',{name:'Revoke fixture',exact:true}).click();await expect(page.locator('#frame iframe')).toHaveCount(0);await page.getByRole('button',{name:'Send retired request'}).click();await page.getByRole('button',{name:'Mount hostile fixture'}).click();await expect(frame.getByRole('heading')).toHaveText('Hostile protocol fixture');await page.getByRole('button',{name:'Send retired request'}).click();await page.waitForTimeout(100);await page.getByRole('button',{name:'Read boundary counts'}).click();await expect(page.locator('#attack-status')).toContainText('writes=0');await expect(frame.getByRole('heading')).toHaveText('Hostile protocol fixture');
});
test('RPC-02 actual in-flight overflow aborts dispatch and SDK dispose cancels pending replies',async({page})=>{
 await page.goto('/spikes/hostile.html');await page.getByRole('button',{name:'Mount slow fixture'}).click();const frame=page.frameLocator('#frame iframe');await expect(frame.getByRole('heading')).toHaveText('Hostile protocol fixture');await frame.getByRole('button',{name:'Overflow in-flight calls'}).click();await expect(page.locator('#frame iframe')).toHaveCount(0);await expect(page.locator('#status')).toHaveText('Revoked; writes=64; cancelled=64');await page.getByRole('button',{name:'Mount slow fixture'}).click();await expect(frame.getByRole('heading')).toHaveText('Hostile protocol fixture');await frame.getByRole('button',{name:'Cancel SDK calls'}).click();await expect(frame.locator('#result')).toHaveText('cancelled');await page.getByRole('button',{name:'Revoke fixture',exact:true}).click();await expect(page.locator('#status')).toHaveText('Revoked; writes=1; cancelled=1');
});
