import {test,expect,type Page} from '@playwright/test';
import {tsImport} from 'tsx/esm/api';
import {getTrustedRoot} from '@sigstore/tuf';
import {toTrustMaterial} from '@sigstore/verify';
import {mkdir,writeFile,readFile,rename} from 'node:fs/promises';
import {resolve} from 'node:path';
import Ajv2020 from 'ajv/dist/2020.js';
const repository='https://github.com/StevenBuglione/pwacloud';
const expectedTag=process.env.PWACLOUD_EXPECTED_PUBLIC_TAG!,expectedCommit=process.env.PWACLOUD_EXPECTED_PUBLIC_COMMIT!;
const expectedHostCommit=process.env.PWACLOUD_EXPECTED_HOST_COMMIT!;
const expectedIdentity=`${repository}/.github/workflows/plugin-release.yml@refs/tags/${expectedTag}`;
type EngineResult={engine:string;status:string;runId:string;hostCommit:string;tag:string;sourceCommit:string;completedAt:string;assertionsCompleted:boolean};
const isEngineResult=new Ajv2020({strict:true}).compile<EngineResult>({type:'object',additionalProperties:false,required:['engine','status','runId','hostCommit','tag','sourceCommit','completedAt','assertionsCompleted'],properties:{engine:{enum:['chromium','webkit']},status:{enum:['passed','failed']},runId:{type:'string'},hostCommit:{type:'string',pattern:'^[a-f0-9]{40}$'},tag:{type:'string'},sourceCommit:{type:'string',pattern:'^[a-f0-9]{40}$'},completedAt:{type:'string'},assertionsCompleted:{type:'boolean'}}});
let assertionsCompleted=false,engineStatus='failed',runId='';
async function atomicJson(path:string,value:unknown){const temporary=`${path}.${process.pid}.tmp`;await writeFile(temporary,JSON.stringify(value,null,2)+'\n');await rename(temporary,path);}
test.beforeAll(async(_fixtures,testInfo)=>{const configured:unknown=testInfo.config.metadata.publicRunId;if(typeof configured!=='string'||!/^[a-f0-9-]{36}$/.test(configured))throw new Error('Fresh public verification run metadata was unavailable');runId=configured;});
test.afterEach(async(_fixtures,testInfo)=>{engineStatus=testInfo.status??'failed';});
test.afterAll(async(_fixtures,testInfo)=>{
  await mkdir('evidence/M3',{recursive:true});const result:EngineResult={engine:testInfo.project.name,status:engineStatus==='passed'&&assertionsCompleted?'passed':'failed',runId,hostCommit:expectedHostCommit,tag:expectedTag,sourceCommit:expectedCommit,completedAt:new Date().toISOString(),assertionsCompleted};
  await atomicJson(`evidence/M3/${testInfo.project.name}-public-status.json`,result);
  const results:EngineResult[]=[];for(const engine of ['chromium','webkit']){try{const value:unknown=JSON.parse(await readFile(`evidence/M3/${engine}-public-status.json`,'utf8'));if(isEngineResult(value)&&value.runId===runId&&value.hostCommit===expectedHostCommit&&value.engine===engine&&value.tag===expectedTag&&value.sourceCommit===expectedCommit)results.push(value);}catch(error){if(!(error instanceof Error&&'code'in error&&error.code==='ENOENT'))throw error;}}
  await atomicJson('evidence/M3/public-install-results.json',{hostCommit:expectedHostCommit,runId,status:results.length===2&&results.every(result=>result.status==='passed')?'passed':'incomplete',results});
});
async function submitPacket(page:Page,packet:unknown,pluginId:string,grants:string[]){
  return page.evaluate(async({packet,pluginId,grants})=>{
    const sessionResponse=await fetch('/v1/session',{credentials:'same-origin'});if(!sessionResponse.ok)throw new Error('Personal runtime session was unavailable');const session:unknown=await sessionResponse.json();
    if(typeof session!=='object'||session===null||!('csrfToken'in session)||typeof session.csrfToken!=='string')throw new Error('Personal session metadata was invalid');
    const readRegistration=async()=>{const response=await fetch(`/v1/installs/${encodeURIComponent(pluginId)}/registration`,{credentials:'same-origin'});if(response.status===404)return null;if(!response.ok)throw new Error('Runtime registration lookup failed');const value:unknown=await response.json();if(typeof value!=='object'||value===null||!('generation'in value)||typeof value.generation!=='number'||!Number.isSafeInteger(value.generation)||!('digest'in value)||typeof value.digest!=='string'||!('state'in value)||typeof value.state!=='string')throw new Error('Runtime registration metadata was invalid');return{generation:value.generation,digest:value.digest,state:value.state};};
    const before=await readRegistration();const response=await fetch('/v1/installs',{method:'POST',credentials:'same-origin',headers:{'content-type':'application/json','x-csrf-token':session.csrfToken},body:JSON.stringify({packet,grants,...(before?{expectedGeneration:before.generation}:{})})});
    const value:unknown=await response.json();const code=typeof value==='object'&&value!==null&&'code'in value&&typeof value.code==='string'?value.code:null;
    return{status:response.status,code,before,after:await readRegistration()};
  },{packet,pluginId,grants});
}
test('PKG-03 actual public Sigstore release resolves installs saves and survives reopen without demo trust',async({page},testInfo)=>{
  const verifier:typeof import('../../packages/package-verifier/src/index')=await tsImport('../../packages/package-verifier/src/index.ts',import.meta.url);
  const provenance:typeof import('../../packages/package-verifier/src/provenance')=await tsImport('../../packages/package-verifier/src/provenance.ts',import.meta.url);
  const registry:typeof import('../../packages/registry-client/src/server')=await tsImport('../../packages/registry-client/src/server.ts',import.meta.url);
  const startedAt=new Date().toISOString();const release=await registry.downloadAttestedGitHubRelease(repository);
  expect(release.sourceRef).toBe(`refs/tags/${expectedTag}`);expect(release.sourceCommit).toBe(expectedCommit);
  const envelope=verifier.parseJson(release.input.envelopeBytes);const contracts:typeof import('../../packages/contracts/src/index')=await tsImport('../../packages/contracts/src/index.ts',import.meta.url);
  if(!contracts.isEnvelope(envelope))throw new Error('The public release envelope was invalid');
  const trusted=toTrustMaterial(await getTrustedRoot({cachePath:resolve('artifacts/public-release-tuf'),timeout:15000,retry:{retries:1}}));
  const policy={issuer:'https://token.actions.githubusercontent.com' as const,workflowIdentity:expectedIdentity,builderId:expectedIdentity,repository,sourceCommit:expectedCommit,workflowPath:'.github/workflows/plugin-release.yml',sourceRef:`refs/tags/${expectedTag}`};
  provenance.verifySigstoreBlob(release.input.archiveBundle,release.input.archiveBytes,trusted,policy);provenance.verifySigstoreBlob(release.input.envelopeBundle,release.input.envelopeBytes,trusted,policy);provenance.verifySigstoreProvenance(release.input.provenanceBundle,trusted,envelope,policy,await verifier.sha256(release.input.envelopeBytes));
  let pageErrors=0;const providerMutations:string[]=[];page.on('pageerror',()=>pageErrors++);page.on('request',request=>{const path=new URL(request.url()).pathname;if(request.method()!=='GET'&&(path==='/v1/runs'||path.startsWith('/v1/provider/')))providerMutations.push(path);});
  await page.goto('/');await expect(page.getByText('Local workspace ready',{exact:true})).toBeVisible();
  const build=await page.evaluate(async()=>{const response=await fetch('/build-info.json');if(!response.ok)throw new Error('Reviewed production build metadata was unavailable');const value:unknown=await response.json();if(typeof value!=='object'||value===null||!('sourceCommit'in value)||typeof value.sourceCommit!=='string'||!('changedSource'in value)||!Array.isArray(value.changedSource)||!value.changedSource.every(path=>typeof path==='string'))throw new Error('Production build metadata was invalid');return{sourceCommit:value.sourceCommit,changedSource:value.changedSource};});expect(build.sourceCommit).toBe(expectedHostCommit);expect(build.changedSource).toEqual([]);
  const runtime=await page.evaluate(async()=>{const response=await fetch('/health');if(!response.ok)throw new Error('Runtime health was unavailable');const value:unknown=await response.json();return typeof value==='object'&&value!==null&&'mode'in value&&'demoOnly'in value?{mode:value.mode,demoOnly:value.demoOnly}:null;});
  expect(runtime).toEqual({mode:'chatgpt-plan-local',demoOnly:false});
  const initialTrust:unknown=await page.evaluate(async()=>{const response=await fetch('/v1/trust',{credentials:'same-origin'});if(!response.ok)throw new Error('Authenticated trust route was unavailable');return response.json();});const initialRoots=Array.isArray(initialTrust)&&initialTrust.length===0?[]:verifier.validateTrustRoots(initialTrust);expect(initialRoots.every(root=>!root.demoOnly)).toBe(true);
  await page.getByRole('navigation',{name:'Main navigation'}).getByRole('button',{name:'Discover',exact:true}).click();await page.getByLabel('GitHub repository URL').fill(repository);await expect(page.getByLabel('GitHub repository URL')).toHaveValue(repository);
  const resolved=page.waitForResponse(response=>new URL(response.url()).pathname==='/v1/registry/resolve');await page.getByRole('button',{name:'Resolve repository',exact:true}).click();const response=await resolved;expect(response.status()).toBe(200);const packet:unknown=await response.json();
  const roots=verifier.validateTrustRoots(await page.evaluate(async()=>{const response=await fetch('/v1/trust',{credentials:'same-origin'});if(!response.ok)throw new Error('Refreshed trust route was unavailable');return response.json();}));expect(roots.every(root=>!root.demoOnly)).toBe(true);
  const pkg=await verifier.verifyInstallPacket(packet,roots,{expectedRepository:repository});expect(pkg.manifest.id).toBe('dev.stevenbuglione.notebook');expect(pkg.envelope.sourceCommit).toBe(expectedCommit);expect(pkg.receipt.publisherIdentity).toBe(expectedIdentity);expect(pkg.receipt.policyVersion).toBe('pwacloud.sigstore-local.v1');expect(pkg.receipt.keyId).toMatch(/^pwacloud-local-[a-f0-9]{32}$/);expect(pkg.envelope.archive.sha256).toBe(await verifier.sha256(release.input.archiveBytes));expect(await verifier.sha256(pkg.packet.envelopeBytes)).toBe(await verifier.sha256(release.input.envelopeBytes));
  const dialog=page.getByRole('dialog');await expect(dialog.getByRole('heading',{name:'Review Notebook',exact:true})).toBeVisible();await expect(dialog.getByText(expectedIdentity,{exact:true})).toBeVisible();
  const grants=pkg.manifest.permissions.filter(permission=>permission.required).map(permission=>permission.id);const altered=new Uint8Array(pkg.packet.envelopeSignature);altered[0]=(altered[0]??0)^1;const tampered=verifier.encodeInstallPacket({...pkg.packet,envelopeSignature:altered});
  await expect(verifier.verifyInstallPacket(tampered,roots,{expectedRepository:repository})).rejects.toThrow(/invalid-signature/);
  const rejection=await submitPacket(page,tampered,pkg.manifest.id,grants);expect(rejection.status).toBe(403);expect(rejection.code).toBe('invalid-signature');expect(rejection.after).toEqual(rejection.before);
  await dialog.getByRole('button',{name:'Install reviewed app',exact:true}).click();await expect(dialog.getByRole('heading',{name:'Notebook is ready',exact:true})).toBeVisible();
  const registration=await submitPacket(page,packet,pkg.manifest.id,grants);expect(registration.status).toBe(200);expect(registration.after?.digest).toBe(pkg.envelope.archive.sha256);expect(registration.after?.state).toBe('active');
  await dialog.getByRole('button',{name:'Open Notebook',exact:true}).click();const frame=page.frameLocator('iframe');await expect(frame.getByRole('heading',{name:'Notebook',exact:true})).toBeVisible();await expect(frame.getByText('Local notes ready',{exact:true})).toBeVisible();await expect(page.locator('iframe')).toHaveAttribute('sandbox','allow-scripts');
  const note='Public signed Notebook saves local content.';await frame.getByLabel('Title',{exact:true}).fill('Public release verification');await frame.getByLabel('Note text',{exact:true}).fill(note);await expect(frame.getByText('Saved on this device',{exact:true})).toBeVisible();
  await frame.getByRole('button',{name:'Analyze with Wasm',exact:true}).click();await expect(frame.getByLabel('Wasm analysis')).toContainText('"words":6');await expect(frame.getByLabel('Wasm analysis')).toContainText('Rust Component Model Wasm');
  await page.getByRole('button',{name:'Back to Library',exact:true}).click();await expect(page.getByRole('heading',{name:'Library',exact:true})).toBeVisible();await page.reload();await expect(page.getByText('Local workspace ready',{exact:true})).toBeVisible();await page.getByRole('button',{name:/^Notebook Rich local/}).click();await expect(frame.getByLabel('Title',{exact:true})).toHaveValue('Public release verification');await expect(frame.getByLabel('Note text',{exact:true})).toHaveValue(note);
  expect(await frame.locator('body').evaluate(body=>body.scrollWidth<=360)).toBe(true);expect(providerMutations).toEqual([]);expect(pageErrors).toBe(0);
  await mkdir('evidence/M3',{recursive:true});await page.screenshot({path:`evidence/M3/${testInfo.project.name}-public-notebook.png`,fullPage:true});
  await atomicJson(`evidence/M3/${testInfo.project.name}-public-install.json`,{startedAt,completedAt:new Date().toISOString(),runId,hostCommit:build.sourceCommit,engine:testInfo.project.name,viewportCssPx:360,repository,tag:expectedTag,sourceCommit:pkg.envelope.sourceCommit,archiveSha256:pkg.envelope.archive.sha256,envelopeSha256:await verifier.sha256(pkg.packet.envelopeBytes),publisherIdentity:pkg.receipt.publisherIdentity,policyVersion:pkg.receipt.policyVersion,receiptKeyId:pkg.receipt.keyId,receiptExpiresAt:pkg.receipt.expiresAt,demoTrust:false,runtimeMode:runtime?.mode,sigstoreArchiveVerified:true,sigstoreEnvelopeVerified:true,slsaSourceVerified:true,repositoryUrlEntered:true,uiInstall:true,runtimeInstallVerification:true,tamperedEnvelopeRejected:true,noteSavedAndReopened:true,actualWasmAnalysisWords:6,aiOrProviderMutations:providerMutations.length,physicalDeviceVerified:false});assertionsCompleted=true;
});
