import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import { PlatformError } from '../../../packages/contracts/src/index';
import { parseJson,verifyExactSignature,type TrustRoot } from '../../../packages/package-verifier/src/index';
export type CatalogueEntry={id:string;title:string;description:string;publisherIdentity:string;repository:string;version:string;digest:string;hostApi:{major:number;minimumMinor:number};profile:'isolated-web'|'host-rendered';capabilities:string[];provides:string[];categories:string[];offline:boolean;language:string;accessibility:'not-reviewed'|'automated-reviewed'|'device-reviewed';moderation:'approved'|'withdrawn';screenshots:string[];verification:{attested:boolean;reproduced:boolean}};
export type Catalogue={format:'pwacloud.catalogue.v1';keyId:string;sequence:number;issuedAt:string;expiresAt:string;revokedDigests:string[];entries:CatalogueEntry[]};
const ajv=new Ajv2020({strict:true});addFormats(ajv);
const text={type:'string',maxLength:240},strings={type:'array',maxItems:32,uniqueItems:true,items:text};
const validate=ajv.compile<Catalogue>({type:'object',additionalProperties:false,required:['format','keyId','sequence','issuedAt','expiresAt','revokedDigests','entries'],properties:{format:{const:'pwacloud.catalogue.v1'},keyId:text,sequence:{type:'integer',minimum:0},issuedAt:{type:'string',format:'date-time'},expiresAt:{type:'string',format:'date-time'},revokedDigests:{type:'array',maxItems:4096,uniqueItems:true,items:{type:'string',pattern:'^[0-9a-f]{64}$'}},entries:{type:'array',maxItems:2048,items:{type:'object',additionalProperties:false,required:['id','title','description','publisherIdentity','repository','version','digest','hostApi','profile','capabilities','provides','categories','offline','language','accessibility','moderation','screenshots','verification'],properties:{id:text,title:text,description:{type:'string',maxLength:1024},publisherIdentity:{type:'string',maxLength:1024},repository:{type:'string',pattern:'^https://github\\.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$'},version:text,digest:{type:'string',pattern:'^[0-9a-f]{64}$'},hostApi:{type:'object',additionalProperties:false,required:['major','minimumMinor'],properties:{major:{type:'integer',minimum:0},minimumMinor:{type:'integer',minimum:0}}},profile:{enum:['isolated-web','host-rendered']},capabilities:strings,provides:strings,categories:strings,offline:{type:'boolean'},language:text,accessibility:{enum:['not-reviewed','automated-reviewed','device-reviewed']},moderation:{enum:['approved','withdrawn']},screenshots:{type:'array',maxItems:8,items:{type:'string',pattern:'^screenshots/[a-z0-9._/-]+\\.(png|webp)$'}},verification:{type:'object',additionalProperties:false,required:['attested','reproduced'],properties:{attested:{type:'boolean'},reproduced:{type:'boolean'}}}}}}}});
export async function verifyCatalogue(bytes:Uint8Array,signature:Uint8Array,roots:readonly TrustRoot[],options:{now?:Date;minimumSequence?:number;allowDemo?:boolean;allowExpiredForCache?:boolean}={}):Promise<Catalogue> {const catalogue=parseJson(bytes,2*1024*1024);if(!validate(catalogue)) throw new PlatformError('invalid-catalogue');const root=roots.find(r=>r.keyId===catalogue.keyId);if(!root || roots.filter(r=>r.keyId===catalogue.keyId).length!==1 || root.demoOnly&&!options.allowDemo) throw new PlatformError('untrusted-catalogue');await verifyExactSignature(bytes,signature,root);const now=(options.now??new Date()).getTime();if(!Number.isFinite(now)||Date.parse(catalogue.issuedAt)>now || !options.allowExpiredForCache&&Date.parse(catalogue.expiresAt)<=now || Date.parse(catalogue.expiresAt)<=Date.parse(catalogue.issuedAt)) throw new PlatformError('expired-catalogue');if(catalogue.sequence<(options.minimumSequence??0)) throw new PlatformError('stale-catalogue');const identities=new Set<string>();for(const entry of catalogue.entries) {if(identities.has(`${entry.id}@${entry.version}`) || entry.publisherIdentity!==root.publisherIdentity) throw new PlatformError('catalogue-identity-mismatch');identities.add(`${entry.id}@${entry.version}`);}return catalogue;}
export function searchCatalogue(catalogue:Catalogue,filter:{query?:string;profile?:CatalogueEntry['profile'];capability?:string;interface?:string;offline?:boolean;language?:string;accessibility?:CatalogueEntry['accessibility']}={}):CatalogueEntry[] {const query=(filter.query??'').trim().toLowerCase();return catalogue.entries.filter(e=>e.moderation==='approved'&&!catalogue.revokedDigests.includes(e.digest)&&e.hostApi.major===1&&e.hostApi.minimumMinor<=0&&(!filter.profile||e.profile===filter.profile)&&(!filter.capability||e.capabilities.includes(filter.capability))&&(!filter.interface||e.provides.includes(filter.interface))&&(filter.offline===undefined||e.offline===filter.offline)&&(!filter.language||e.language===filter.language)&&(!filter.accessibility||e.accessibility===filter.accessibility)&&(!query||`${e.title} ${e.description} ${e.categories.join(' ')}`.toLowerCase().includes(query))).sort((a,b)=>{const score=(e:CatalogueEntry)=>query&&e.title.toLowerCase().includes(query)?1:0;return score(b)-score(a)||a.title.localeCompare(b.title);});}
export function revocationFreshness(catalogue:Catalogue,now=new Date()):'current'|'stale' {return Date.parse(catalogue.expiresAt)>now.getTime()?'current':'stale';}
