import { PlatformError } from '../../contracts/src/index';
import { verifyInstallPacket,verifyPackage,type PackageInput,type TrustRoot,type VerifiedPackage,type VerificationOptions } from '../../package-verifier/src/index';
export { resolveDependencyGraph } from './dependencies';
export type RegistryTransport=(repository:string,signal?:AbortSignal)=>Promise<unknown>;
export type RegistryConfig={roots:readonly TrustRoot[];transport?:RegistryTransport;options?:VerificationOptions|(()=>VerificationOptions)};
export function canonicalRepository(value:string):string {const match=/^https:\/\/github\.com\/([A-Za-z0-9_.-]+)\/([A-Za-z0-9_.-]+?)(?:\.git)?\/?$/.exec(value);if(!match || match[1]==='.' || match[1]==='..' || match[2]==='.' || match[2]==='..') throw new PlatformError('unsupported-repository');return `https://github.com/${match[1]}/${match[2]}`;}
export class RegistryClient {
  constructor(private readonly config:RegistryConfig) {}
  async resolveRepository(repository:string,signal?:AbortSignal):Promise<VerifiedPackage> {repository=canonicalRepository(repository);const transport=this.config.transport??(async (repo:string,abort?:AbortSignal)=>{const response=await fetch(`/v1/registry/resolve?repository=${encodeURIComponent(repo)}`,{credentials:'same-origin',signal:abort});if(!response.ok) throw new PlatformError('resolve-failed');return response.json() as Promise<unknown>;});const packet=await transport(repository,signal),options=typeof this.config.options==='function'?this.config.options():this.config.options;return verifyInstallPacket(packet,this.config.roots,{...options,expectedRepository:repository});}
}
export async function resolveRepository(repository:string,roots:readonly TrustRoot[],signal?:AbortSignal,options?:VerificationOptions):Promise<VerifiedPackage> {return new RegistryClient({roots,options}).resolveRepository(repository,signal);}
export async function loadFixture(id:string,roots:readonly TrustRoot[],signal?:AbortSignal,options:VerificationOptions={}):Promise<VerifiedPackage> {if(!/^[a-z0-9-]+$/.test(id)) throw new PlatformError('invalid-fixture');const names=['archive.zip','envelope.json','receipt.json','receipt.sig','envelope.sig'];const bytes=await Promise.all(names.map(async name=>{const response=await fetch(`/fixtures/${id}/${name}`,{signal});if(!response.ok) throw new PlatformError('fixture-unavailable');return new Uint8Array(await response.arrayBuffer());}));const [archiveBytes,envelopeBytes,receiptBytes,signature,envelopeSignature]=bytes;if(!archiveBytes || !envelopeBytes || !receiptBytes || !signature || !envelopeSignature) throw new PlatformError('fixture-unavailable');const input:PackageInput={archiveBytes,envelopeBytes,receiptBytes,signature,envelopeSignature};return verifyPackage(input,roots,{allowDemo:true,...options});}
