import Ajv2020 from 'ajv/dist/2020.js';
import {PlatformError} from '../../contracts/src/index';
import {encodeInstallPacket,parseJson,sha256,verifyPackage,type PackageInput,type TrustRoot,type VerificationOptions} from '../../package-verifier/src/index';
import type {SecureFetchOptions,SecureResponse} from './secure-fetch';
type Download=(url:string,options?:SecureFetchOptions)=>Promise<SecureResponse>;
const ajv=new Ajv2020({strict:true});
type OciManifest={schemaVersion:2;mediaType:'application/vnd.oci.image.manifest.v1+json';artifactType:'application/vnd.pwacloud.plugin.v1';config:{mediaType:string;digest:string;size:number};layers:{mediaType:string;digest:string;size:number;annotations:{'org.opencontainers.image.title':string}}[]};
const ociValidator=ajv.compile<OciManifest>({type:'object',additionalProperties:false,required:['schemaVersion','mediaType','artifactType','config','layers'],properties:{schemaVersion:{const:2},mediaType:{const:'application/vnd.oci.image.manifest.v1+json'},artifactType:{const:'application/vnd.pwacloud.plugin.v1'},config:{type:'object',additionalProperties:false,required:['mediaType','digest','size'],properties:{mediaType:{const:'application/vnd.oci.empty.v1+json'},digest:{type:'string',pattern:'^sha256:[0-9a-f]{64}$'},size:{type:'integer',minimum:0,maximum:1024}}},layers:{type:'array',minItems:5,maxItems:5,items:{type:'object',additionalProperties:false,required:['mediaType','digest','size','annotations'],properties:{mediaType:{enum:['application/zip','application/json','application/octet-stream']},digest:{type:'string',pattern:'^sha256:[0-9a-f]{64}$'},size:{type:'integer',minimum:1,maximum:67108864},annotations:{type:'object',additionalProperties:false,required:['org.opencontainers.image.title'],properties:{'org.opencontainers.image.title':{enum:['archive.zip','envelope.json','receipt.json','receipt.sig','envelope.sig']}}}}}}}});
export async function resolveOciWithTransport(reference:string,roots:readonly TrustRoot[],signal:AbortSignal|undefined,options:VerificationOptions,download:Download):Promise<Record<string,string>> {
  const match=/^oci:\/\/([a-z0-9.-]+)\/([a-z0-9._/-]+)@(sha256:[0-9a-f]{64})$/.exec(reference);if(!match || match[2]?.split('/').some(p=>!p || p==='.' || p==='..')) throw new PlatformError('invalid-oci-reference');const origin=`https://${match[1]}`,base=`${origin}/v2/${match[2]}`;const response=await download(`${base}/manifests/${match[3]}`,{signal,maximumBytes:262144,allowedOrigins:[origin],headers:{Accept:'application/vnd.oci.image.manifest.v1+json'}});if(response.status!==200 || `sha256:${await sha256(response.bytes)}`!==match[3]) throw new PlatformError('oci-manifest-mismatch');const manifest=parseJson(response.bytes);if(!ociValidator(manifest)) throw new PlatformError('invalid-oci-manifest');
  const files=new Map<string,Uint8Array>();
  for(const layer of manifest.layers) {const name=layer.annotations['org.opencontainers.image.title'];if(files.has(name)) throw new PlatformError('duplicate-oci-layer');const result=await download(`${base}/blobs/${layer.digest}`,{signal,maximumBytes:layer.size,allowedOrigins:[origin]});if(result.status!==200 || result.bytes.length!==layer.size || `sha256:${await sha256(result.bytes)}`!==layer.digest) throw new PlatformError('oci-layer-mismatch');files.set(name,result.bytes);}
  const archiveBytes=files.get('archive.zip'),envelopeBytes=files.get('envelope.json'),receiptBytes=files.get('receipt.json'),signature=files.get('receipt.sig'),envelopeSignature=files.get('envelope.sig');if(!archiveBytes || !envelopeBytes || !receiptBytes || !signature || !envelopeSignature) throw new PlatformError('missing-oci-layer');const input:PackageInput={archiveBytes,envelopeBytes,receiptBytes,signature,envelopeSignature};await verifyPackage(input,roots,options);return encodeInstallPacket(input);
}

