import {resolveOciWithTransport} from './oci';
import Ajv2020 from 'ajv/dist/2020.js';
import { PlatformError } from '../../contracts/src/index';
import { decodeBase64,encodeInstallPacket,parseJson,verifyPackage,type PackageInput,type TrustRoot,type VerificationOptions } from '../../package-verifier/src/index';
import { canonicalRepository } from './index';
import { secureFetch,type SecureFetchOptions,type SecureResponse } from './secure-fetch';
import type { AttestedRelease } from '../../package-verifier/src/provenance';
import type { VerifiedPackage } from '../../package-verifier/src/index';
export { secureFetch,isPublicAddress } from './secure-fetch';
export type Download=(url:string,options?:SecureFetchOptions)=>Promise<SecureResponse>;
export type AttestedReceiptIssuer=(release:{input:AttestedRelease;sourceCommit:string;sourceRef:string})=>Promise<VerifiedPackage>;
const ajv=new Ajv2020({strict:true});
type GitHubRelease={tag_name:string;target_commitish:string;draft:boolean;prerelease:boolean;assets:{name:string;browser_download_url:string;size:number}[]};
const releaseValidator=ajv.compile<GitHubRelease>({type:'object',required:['tag_name','target_commitish','draft','prerelease','assets'],properties:{tag_name:{type:'string'},target_commitish:{type:'string'},draft:{type:'boolean'},prerelease:{type:'boolean'},assets:{type:'array',maxItems:128,items:{type:'object',required:['name','browser_download_url','size'],properties:{name:{type:'string',maxLength:120},browser_download_url:{type:'string',maxLength:8192},size:{type:'integer',minimum:0,maximum:67108864}}}}}});
const commitValidator=ajv.compile<{sha:string}>({type:'object',required:['sha'],properties:{sha:{type:'string',pattern:'^[0-9a-f]{40}$'}}});
export async function downloadAttestedGitHubRelease(repository:string,plugin:'notebook'|'feed-reader'|'canvas-board'='notebook',signal?:AbortSignal,download:Download=secureFetch):Promise<{input:AttestedRelease;sourceCommit:string;sourceRef:string}> {
  repository=canonicalRepository(repository);const response=await download(`https://api.github.com/repos/${repository.slice('https://github.com/'.length)}/releases/latest`,{signal,maximumBytes:1048576,allowedOrigins:['https://api.github.com']});if(response.status!==200) throw new PlatformError('release-unavailable');const release=parseJson(response.bytes,1048576);if(!releaseValidator(release) || release.draft || release.prerelease) throw new PlatformError('invalid-release');
  const names=[`${plugin}.archive.zip`,`${plugin}.envelope.json`,`${plugin}.archive.zip.sigstore.json`,`${plugin}.envelope.json.sigstore.json`,'provenance.sigstore.json'];
  const bytes=await Promise.all(names.map(async name=>{const assets=release.assets.filter(a=>a.name===name),asset=assets[0];if(assets.length!==1 || !asset) throw new PlatformError('missing-release-asset');const url=new URL(asset.browser_download_url);if(url.origin!=='https://github.com' || !url.pathname.startsWith(`${new URL(repository).pathname}/releases/download/${encodeURIComponent(release.tag_name)}/`)) throw new PlatformError('release-source-mismatch');const result=await download(url.href,{signal,maximumBytes:name.endsWith('.zip')?67108864:1048576,allowedOrigins:['https://github.com','https://release-assets.githubusercontent.com','https://objects.githubusercontent.com']});if(result.status!==200 || result.bytes.length!==asset.size) throw new PlatformError('release-download-failed');return result.bytes;}));
  const [archiveBytes,envelopeBytes,archiveBundleBytes,envelopeBundleBytes,provenanceBundleBytes]=bytes;if(!archiveBytes || !envelopeBytes || !archiveBundleBytes || !envelopeBundleBytes || !provenanceBundleBytes) throw new PlatformError('missing-release-asset');
  const tag=await download(`https://api.github.com/repos/${repository.slice('https://github.com/'.length)}/commits/${encodeURIComponent(release.tag_name)}`,{signal,maximumBytes:1048576,allowedOrigins:['https://api.github.com']});const commit=parseJson(tag.bytes,1048576);if(tag.status!==200 || !commitValidator(commit)) throw new PlatformError('release-commit-mismatch');
  return {input:{archiveBytes,envelopeBytes,archiveBundle:parseJson(archiveBundleBytes,1048576),envelopeBundle:parseJson(envelopeBundleBytes,1048576),provenanceBundle:parseJson(provenanceBundleBytes,1048576)},sourceCommit:commit.sha,sourceRef:`refs/tags/${release.tag_name}`};
}
export async function resolveGitHubRepository(repository:string,roots:readonly TrustRoot[],signal?:AbortSignal,options:VerificationOptions={},download:Download=secureFetch,attestedIssuer?:AttestedReceiptIssuer):Promise<Record<string,string>> {
  repository=canonicalRepository(repository);const response=await download(`https://api.github.com/repos/${repository.slice('https://github.com/'.length)}/releases/latest`,{signal,maximumBytes:1048576,allowedOrigins:['https://api.github.com']});if(response.status!==200) throw new PlatformError('release-unavailable');const release=parseJson(response.bytes,1048576);if(!releaseValidator(release) || release.draft || release.prerelease) throw new PlatformError('invalid-release');
  const names=['archive.zip','envelope.json','receipt.json','receipt.sig','envelope.sig'];
  if(!names.every(name=>release.assets.some(a=>a.name===name))) {if(!attestedIssuer) throw new PlatformError('receipt-issuer-not-configured');const attested=await downloadAttestedGitHubRelease(repository,'notebook',signal,download);const verified=await attestedIssuer(attested);await verifyPackage(verified.packet,roots,{...options,expectedRepository:repository});return encodeInstallPacket(verified.packet);}
  const bytes=await Promise.all(names.map(async name=>{const assets=release.assets.filter(a=>a.name===name);const asset=assets[0];if(assets.length!==1 || !asset) throw new PlatformError('missing-release-asset');const url=new URL(asset.browser_download_url);if(url.origin!=='https://github.com' || !url.pathname.startsWith(`${new URL(repository).pathname}/releases/download/${encodeURIComponent(release.tag_name)}/`)) throw new PlatformError('release-source-mismatch');const result=await download(url.href,{signal,maximumBytes:name==='archive.zip'?67108864:262144,allowedOrigins:['https://github.com','https://release-assets.githubusercontent.com','https://objects.githubusercontent.com']});if(result.status!==200 || result.bytes.length!==asset.size) throw new PlatformError('release-download-failed');return result.bytes;}));
  const [archiveBytes,envelopeBytes,receiptBytes,signature,envelopeSignature]=bytes;if(!archiveBytes || !envelopeBytes || !receiptBytes || !signature || !envelopeSignature) throw new PlatformError('missing-release-asset');const input:PackageInput={archiveBytes,envelopeBytes,receiptBytes,signature,envelopeSignature};const verified=await verifyPackage(input,roots,{...options,expectedRepository:repository});
  const tag=await download(`https://api.github.com/repos/${repository.slice('https://github.com/'.length)}/commits/${encodeURIComponent(release.tag_name)}`,{signal,maximumBytes:1048576,allowedOrigins:['https://api.github.com']});const commit=parseJson(tag.bytes,1048576);if(tag.status!==200 || !commitValidator(commit) || commit.sha!==verified.envelope.sourceCommit) throw new PlatformError('release-commit-mismatch');
  return encodeInstallPacket(input);
}
export function resolveOci(reference:string,roots:readonly TrustRoot[],signal?:AbortSignal,options:VerificationOptions={},download:Download=secureFetch):Promise<Record<string,string>>{
 return resolveOciWithTransport(reference,roots,signal,options,download);
}
export function decodeSignature(value:string):Uint8Array {const signature=decodeBase64(value);if(signature.length!==64) throw new PlatformError('invalid-signature');return signature;}

