import Ajv2020 from 'ajv/dist/2020.js';
import { PlatformError } from '../../contracts/src/index';
import { decodeBase64,encodeInstallPacket,parseJson,sha256,verifyPackage,type PackageInput,type TrustRoot,type VerificationOptions } from '../../package-verifier/src/index';
import { canonicalRepository } from './index';
import { secureFetch,type SecureFetchOptions,type SecureResponse } from './secure-fetch';
import type { AttestedRelease } from '../../package-verifier/src/provenance';
import type { VerifiedPackage } from '../../package-verifier/src/index';
export { secureFetch,isPublicAddress } from './secure-fetch';
export type Download=(url:string,options?:SecureFetchOptions)=>Promise<SecureResponse>;
export type AttestedReceiptIssuer=(release:{input:AttestedRelease;sourceCommit:string;sourceRef:string})=>Promise<VerifiedPackage>;
const ajv=new Ajv2020({strict:true});
type GitHubRelease={tag_name:string;target_commitish:string;draft:boolean;prerelease:boolean;assets:{name:string;browser_download_url:string;size:number}[]};
const releaseValidator=ajv.compile<GitHubRelease>({type:'object',required:['tag_name','target_commitish','draft','prerelease','assets'],properties:{tag_name:{type:'string'},target_commitish:{type:'string'},draft:{type:'boolean'},prerelease:{type:'boolean'},assets:{type:'array',maxItems:128,items:{type:'object',required:['name','browser_download_url','size'],properties:{name:{type:'string',maxLength:120},browser_download_url:{type:'string',maxLength:8192},size:{type:'integer',minimum:0,maximum:67108864}}}}}});
const commitValidator=ajv.compile<{sha:string}>({type:'object',required:['sha'],properties:{sha:{type:'string',pattern:'^[0-9a-f]{40}$'}}});
export async function downloadAttestedGitHubRelease(repository:string,plugin:'notebook'|'feed-reader'|'canvas-board'='notebook',signal?:AbortSignal,download:Download=secureFetch):Promise<{input:AttestedRelease;sourceCommit:string;sourceRef:string}> {
  repository=canonicalRepository(repository);const response=await download(`https://api.github.com/repos/${repository.slice('https://github.com/'.length)}/releases/latest`,{signal,maximumBytes:1048576,allowedOrigins:['https://api.github.com']});if(response.status!==200) throw new PlatformError('release-unavailable');const release=parseJson(response.bytes,1048576);if(!releaseValidator(release) || release.draft || release.prerelease) throw new PlatformError('invalid-release');
  const names=[`${plugin}.archive.zip`,`${plugin}.envelope.json`,`${plugin}.archive.zip.sigstore.json`,`${plugin}.envelope.json.sigstore.json`,'provenance.sigstore.json'];
  const bytes=await Promise.all(names.map(async name=>{const assets=release.assets.filter(a=>a.name===name),asset=assets[0];if(assets.length!==1 || !asset) throw new PlatformError('missing-release-asset');const url=new URL(asset.browser_download_url);if(url.origin!=='https://github.com' || !url.pathname.startsWith(`${new URL(repository).pathname}/releases/download/${encodeURIComponent(release.tag_name)}/`)) throw new PlatformError('release-source-mismatch');const result=await download(url.href,{signal,maximumBytes:name.endsWith('.zip')?67108864:1048576,allowedOrigins:['https://github.com','https://release-assets.githubusercontent.com','https://objects.githubusercontent.com']});if(result.status!==200 || result.bytes.length!==asset.size) throw new PlatformError('release-download-failed');return result.bytes;}));
  const [archiveBytes,envelopeBytes,archiveBundleBytes,envelopeBundleBytes,provenanceBundleBytes]=bytes;if(!archiveBytes || !envelopeBytes || !archiveBundleBytes || !envelopeBundleBytes || !provenanceBundleBytes) throw new PlatformError('missing-release-asset');
  const tag=await download(`https://api.github.com/repos/${repository.slice('https://github.com/'.length)}/commits/${encodeURIComponent(release.tag_name)}`,{signal,maximumBytes:1048576,allowedOrigins:['https://api.github.com']});const commit=parseJson(tag.bytes,1048576);if(tag.status!==200 || !commitValidator(commit)) throw new PlatformError('release-commit-mismatch');
  return {input:{archiveBytes,envelopeBytes,archiveBundle:parseJson(archiveBundleBytes,1048576),envelopeBundle:parseJson(envelopeBundleBytes,1048576),provenanceBundle:parseJson(provenanceBundleBytes,1048576)},sourceCommit:commit.sha,sourceRef:`refs/tags/${release.tag_name}`};
}
export async function resolveGitHubRepository(repository:string,roots:readonly TrustRoot[],signal?:AbortSignal,options:VerificationOptions={},download:Download=secureFetch,attestedIssuer?:AttestedReceiptIssuer):Promise<Record<string,string>> {
  repository=canonicalRepository(repository);const response=await download(`https://api.github.com/repos/${repository.slice('https://github.com/'.length)}/releases/latest`,{signal,maximumBytes:1048576,allowedOrigins:['https://api.github.com']});if(response.status!==200) throw new PlatformError('release-unavailable');const release=parseJson(response.bytes,1048576);if(!releaseValidator(release) || release.draft || release.prerelease) throw new PlatformError('invalid-release');
  const names=['archive.zip','envelope.json','receipt.json','receipt.sig','envelope.sig'];
  if(!names.every(name=>release.assets.some(a=>a.name===name))) {if(!attestedIssuer) throw new PlatformError('receipt-issuer-not-configured');const attested=await downloadAttestedGitHubRelease(repository,'notebook',signal,download);const verified=await attestedIssuer(attested);await verifyPackage(verified.packet,roots,{...options,expectedRepository:repository});return encodeInstallPacket(verified.packet);}
  const bytes=await Promise.all(names.map(async name=>{const assets=release.assets.filter(a=>a.name===name);const asset=assets[0];if(assets.length!==1 || !asset) throw new PlatformError('missing-release-asset');const url=new URL(asset.browser_download_url);if(url.origin!=='https://github.com' || !url.pathname.startsWith(`${new URL(repository).pathname}/releases/download/${encodeURIComponent(release.tag_name)}/`)) throw new PlatformError('release-source-mismatch');const result=await download(url.href,{signal,maximumBytes:name==='archive.zip'?67108864:262144,allowedOrigins:['https://github.com','https://release-assets.githubusercontent.com','https://objects.githubusercontent.com']});if(result.status!==200 || result.bytes.length!==asset.size) throw new PlatformError('release-download-failed');return result.bytes;}));
  const [archiveBytes,envelopeBytes,receiptBytes,signature,envelopeSignature]=bytes;if(!archiveBytes || !envelopeBytes || !receiptBytes || !signature || !envelopeSignature) throw new PlatformError('missing-release-asset');const input:PackageInput={archiveBytes,envelopeBytes,receiptBytes,signature,envelopeSignature};const verified=await verifyPackage(input,roots,{...options,expectedRepository:repository});
  const tag=await download(`https://api.github.com/repos/${repository.slice('https://github.com/'.length)}/commits/${encodeURIComponent(release.tag_name)}`,{signal,maximumBytes:1048576,allowedOrigins:['https://api.github.com']});const commit=parseJson(tag.bytes,1048576);if(tag.status!==200 || !commitValidator(commit) || commit.sha!==verified.envelope.sourceCommit) throw new PlatformError('release-commit-mismatch');
  return encodeInstallPacket(input);
}
type OciManifest={schemaVersion:2;mediaType:'application/vnd.oci.image.manifest.v1+json';artifactType:'application/vnd.pwacloud.plugin.v1';config:{mediaType:string;digest:string;size:number};layers:{mediaType:string;digest:string;size:number;annotations:{'org.opencontainers.image.title':string}}[]};
const ociValidator=ajv.compile<OciManifest>({type:'object',additionalProperties:false,required:['schemaVersion','mediaType','artifactType','config','layers'],properties:{schemaVersion:{const:2},mediaType:{const:'application/vnd.oci.image.manifest.v1+json'},artifactType:{const:'application/vnd.pwacloud.plugin.v1'},config:{type:'object',additionalProperties:false,required:['mediaType','digest','size'],properties:{mediaType:{const:'application/vnd.oci.empty.v1+json'},digest:{type:'string',pattern:'^sha256:[0-9a-f]{64}$'},size:{type:'integer',minimum:0,maximum:1024}}},layers:{type:'array',minItems:5,maxItems:5,items:{type:'object',additionalProperties:false,required:['mediaType','digest','size','annotations'],properties:{mediaType:{enum:['application/zip','application/json','application/octet-stream']},digest:{type:'string',pattern:'^sha256:[0-9a-f]{64}$'},size:{type:'integer',minimum:1,maximum:67108864},annotations:{type:'object',additionalProperties:false,required:['org.opencontainers.image.title'],properties:{'org.opencontainers.image.title':{enum:['archive.zip','envelope.json','receipt.json','receipt.sig','envelope.sig']}}}}}}}});
export async function resolveOci(reference:string,roots:readonly TrustRoot[],signal?:AbortSignal,options:VerificationOptions={},download:Download=secureFetch):Promise<Record<string,string>> {
  const match=/^oci:\/\/([a-z0-9.-]+)\/([a-z0-9._/-]+)@(sha256:[0-9a-f]{64})$/.exec(reference);if(!match || match[2]?.split('/').some(p=>!p || p==='.' || p==='..')) throw new PlatformError('invalid-oci-reference');const origin=`https://${match[1]}`,base=`${origin}/v2/${match[2]}`;const response=await download(`${base}/manifests/${match[3]}`,{signal,maximumBytes:262144,allowedOrigins:[origin],headers:{Accept:'application/vnd.oci.image.manifest.v1+json'}});if(response.status!==200 || `sha256:${await sha256(response.bytes)}`!==match[3]) throw new PlatformError('oci-manifest-mismatch');const manifest=parseJson(response.bytes);if(!ociValidator(manifest)) throw new PlatformError('invalid-oci-manifest');
  const files=new Map<string,Uint8Array>();
  for(const layer of manifest.layers) {const name=layer.annotations['org.opencontainers.image.title'];if(files.has(name)) throw new PlatformError('duplicate-oci-layer');const result=await download(`${base}/blobs/${layer.digest}`,{signal,maximumBytes:layer.size,allowedOrigins:[origin]});if(result.status!==200 || result.bytes.length!==layer.size || `sha256:${await sha256(result.bytes)}`!==layer.digest) throw new PlatformError('oci-layer-mismatch');files.set(name,result.bytes);}
  const archiveBytes=files.get('archive.zip'),envelopeBytes=files.get('envelope.json'),receiptBytes=files.get('receipt.json'),signature=files.get('receipt.sig'),envelopeSignature=files.get('envelope.sig');if(!archiveBytes || !envelopeBytes || !receiptBytes || !signature || !envelopeSignature) throw new PlatformError('missing-oci-layer');const input:PackageInput={archiveBytes,envelopeBytes,receiptBytes,signature,envelopeSignature};await verifyPackage(input,roots,options);return encodeInstallPacket(input);
}
export function decodeSignature(value:string):Uint8Array {const signature=decodeBase64(value);if(signature.length!==64) throw new PlatformError('invalid-signature');return signature;}
