import { createServer } from 'node:http';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { build,context } from 'esbuild';
import { PlatformError } from '../../contracts/src/index';
import { buildPlugin,validateDirectory } from './index';
export async function startDevelopmentServer(directory:string,port=0):Promise<{url:string;close:()=>Promise<void>}> {
  await buildPlugin(directory,true);const manifest=await validateDirectory(directory);if(!manifest.ui) throw new PlatformError('missing-ui');const root=resolve(directory),entry=await readFile(resolve(root,'src/index.tsx')).then(()=>resolve(root,'src/index.tsx')).catch(()=>resolve(root,'src/index.ts'));
  const ui=context({entryPoints:[entry],bundle:true,format:'iife',platform:'browser',target:'es2022',jsx:'automatic',outfile:resolve(root,'package',manifest.ui.entry),legalComments:'inline'});const watcher=await ui;await watcher.watch();
  const runtime=fileURLToPath(new URL('../../runtime-ui/src/index.ts',import.meta.url));
  const trustedHost=`import Ajv2020 from 'ajv/dist/2020.js';import {mountIsolatedUI} from ${JSON.stringify(runtime)};type Source={bundle:string;css:string;id:string;title:string};const validate=new Ajv2020({strict:true}).compile<Source>({type:'object',additionalProperties:false,required:['bundle','css','id','title'],properties:{bundle:{type:'string',maxLength:20971520},css:{type:'string',maxLength:20971520},id:{type:'string',minLength:1,maxLength:240},title:{type:'string',minLength:1,maxLength:1000}}});let session:ReturnType<typeof mountIsolatedUI>|undefined;let last='';const state=document.getElementById('state');if(!state)throw new Error('Missing preview state');async function refresh(){try{const response=await fetch('/source');if(!response.ok)throw new Error('Build unavailable');const source:unknown=await response.json();if(!validate(source))throw new Error('Invalid source');const revision=source.bundle+source.css;if(revision===last)return;last=revision;session?.close();const container=document.getElementById('preview');if(!container)throw new Error('Missing preview');session=mountIsolatedUI(container,{bundle:source.bundle,css:source.css,title:source.title,principal:{workspace:'development',plugin:source.id,digest:'unsigned-development-source',generation:1,instance:crypto.randomUUID(),connection:crypto.randomUUID()},dispatch:async()=>{throw new Error('Development preview has no host grants; install a verified package to test capabilities.')}});state.textContent='Unsigned source preview. Host capabilities are disabled.';}catch(error){state.textContent='Build failed. Check terminal diagnostics.';console.error('Development preview failed',error);}}await refresh();setInterval(refresh,1000);window.addEventListener('pagehide',()=>session?.close());`;
  const host=await build({stdin:{contents:trustedHost,loader:'ts',resolveDir:process.cwd()},bundle:true,format:'esm',platform:'browser',target:'es2022',write:false});const hostBytes=host.outputFiles[0]?.contents;if(!hostBytes){await watcher.dispose();throw new PlatformError('missing-development-host');}
  const server=createServer(async(req,res)=>{try {const url=new URL(req.url??'/','http://127.0.0.1');res.setHeader('cache-control','no-store');res.setHeader('x-content-type-options','nosniff');if(req.method!=='GET'){res.writeHead(405);res.end();return;}if(url.pathname==='/'){res.setHeader('content-type','text/html; charset=utf-8');res.end('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PWACloud development preview</title><style>body{margin:0;font:16px system-ui;background:#f3f5f9;color:#182238}header{padding:12px}#preview{width:100%;height:calc(100dvh - 100px)}iframe{width:100%;height:100%;border:0}</style><header><h1 style="font-size:18px">PWACloud development preview</h1><p id="state">Unsigned source preview. Host capabilities are disabled.</p></header><main id="preview"></main><script type="module" src="/host.js"></script></html>');return;}if(url.pathname==='/host.js'){res.setHeader('content-type','text/javascript; charset=utf-8');res.end(hostBytes);return;}if(url.pathname==='/source'){res.setHeader('content-type','application/json');res.end(JSON.stringify({bundle:await readFile(resolve(root,'package',manifest.ui!.entry),'utf8'),css:manifest.ui!.style?await readFile(resolve(root,'src/style.css'),'utf8'):'',id:manifest.id,title:manifest.name}));return;}res.writeHead(404);res.end();}catch{res.writeHead(503);res.end('Build unavailable');}});
  try {await new Promise<void>((resolveReady,reject)=>{server.once('error',reject);server.listen(port,'127.0.0.1',resolveReady);});}catch(error){await watcher.dispose();throw error;}const address=server.address();if(!address||typeof address==='string'){server.close();await watcher.dispose();throw new PlatformError('development-server-failed');}
  return {url:`http://127.0.0.1:${address.port}`,close:async()=>{await watcher.dispose();await new Promise<void>((resolveClosed,reject)=>server.close(error=>error?reject(error):resolveClosed()));}};
}
