import { readFile,writeFile,mkdir,readdir,lstat,access } from 'node:fs/promises';
import { resolve,relative,sep } from 'node:path';
import { execFileSync } from 'node:child_process';
import { build } from 'esbuild';
import Ajv2020 from 'ajv/dist/2020.js';
import { validateManifest,isEnvelope,type Manifest,PlatformError } from '../../contracts/src/index';
import { createEnvelope,parseJson,unpackArchive,verifyPackage,validateTrustRoots,sha256 } from '../../package-verifier/src/index';
const publicationValidator=new Ajv2020({strict:true});
const publicRepository=publicationValidator.compile<{private:false;full_name:'StevenBuglione/pwacloud'}>({type:'object',required:['private','full_name'],properties:{private:{const:false},full_name:{const:'StevenBuglione/pwacloud'}}});
const reviewedCommit=publicationValidator.compile<{sha:string}>({type:'object',required:['sha'],properties:{sha:{type:'string',pattern:'^[0-9a-f]{40}$'}}});
export async function readPackageDirectory(directory:string):Promise<Record<string,Uint8Array>> {
  const root=resolve(directory),files:Record<string,Uint8Array>={};
  async function walk(path:string):Promise<void> {for(const entry of await readdir(path,{withFileTypes:true})) {const child=resolve(path,entry.name),inside=relative(root,child);if(inside.startsWith(`..${sep}`)||inside==='..'||!inside) throw new PlatformError('unsafe-package-source');const info=await lstat(child);if(info.isSymbolicLink() || info.isFile()&&info.nlink>1 || !info.isFile()&&!info.isDirectory()) throw new PlatformError('unsafe-package-source');if(info.isDirectory()) await walk(child);else {if(info.size>20*1024*1024 || Object.keys(files).length>=512) throw new PlatformError('archive-budget');files[inside.split(sep).join('/')]=new Uint8Array(await readFile(child));}}}
  if((await lstat(root)).isSymbolicLink()) throw new PlatformError('unsafe-package-source');await walk(root);return files;
}
export async function packDirectory(directory:string,output:string,commit?:string):Promise<void> {const files=await readPackageDirectory(directory);const sourceCommit=commit??execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim();const result=await createEnvelope(files,sourceCommit);await mkdir(output,{recursive:true});await writeFile(resolve(output,'archive.zip'),result.archiveBytes);await writeFile(resolve(output,'envelope.json'),result.envelopeBytes);}
export async function validateDirectory(directory:string):Promise<Manifest> {const path=resolve(directory,'manifest.json');return validateManifest(parseJson(new Uint8Array(await readFile(path)),131072));}
export async function buildPlugin(directory:string,watch=false):Promise<void> {const manifest=await validateDirectory(directory);if(!manifest.ui || manifest.ui.profile!=='isolated-web') throw new PlatformError('unsupported-ui-build');const root=resolve(directory);let entry=resolve(root,'src/index.tsx');try {await access(entry);} catch {entry=resolve(root,'src/index.ts');}await mkdir(resolve(root,'package/ui'),{recursive:true});await build({entryPoints:[entry],bundle:true,format:'iife',platform:'browser',target:'es2022',minify:!watch,jsx:'automatic',outfile:resolve(root,'package',manifest.ui.entry),legalComments:'inline'});await writeFile(resolve(root,'package/manifest.json'),JSON.stringify(manifest));if(manifest.ui.style) await writeFile(resolve(root,'package',manifest.ui.style),await readFile(resolve(root,'src/style.css')));if(manifest.service) {try {await access(resolve(root,'package',manifest.service.entry));} catch {throw new PlatformError('service-build-required','Compile the Rust component with the pinned trusted pipeline before packing.');}}}
export async function createPlugin(directory:string,id:string,framework:'react'|'lit'='react'):Promise<void> {
  const root=resolve(directory);try {await access(root);throw new PlatformError('directory-exists');} catch(error) {if(error instanceof PlatformError) throw error;}
  const manifest:Manifest={apiVersion:'pwacloud.dev/v0.1',kind:'Plugin',id,name:'New plugin',description:'An original local plugin',version:'0.1.0',license:'MIT',hostApi:{major:1,minimumMinor:0},source:{repository:'https://github.com/OWNER/REPOSITORY',directory:'plugins/new-plugin'},permissions:[{id:'data',capability:'storage.kv',required:true,scope:{quotaBytes:1048576}}],provides:[],requires:[],ui:{profile:'isolated-web',entry:'ui/app.js',style:'ui/style.css',minWidthCssPx:360,contributes:[{type:'library-entry',id:'main',title:'New plugin'}]}};validateManifest(manifest);
  await mkdir(resolve(root,'src'),{recursive:true});await writeFile(resolve(root,'manifest.json'),JSON.stringify(manifest,null,2));
  const source=framework==='react'?"import React from 'react';\nimport {createRoot} from 'react-dom/client';\nconst root=document.getElementById('root');if(!root) throw new Error('Missing mount');\ncreateRoot(root).render(<main><h1>New plugin</h1><label>Text<textarea aria-label=\"Text\"/></label></main>);\n":"import {LitElement,html,css} from 'lit';\nclass PluginView extends LitElement {static styles=css`:host{display:block;font:16px system-ui}main{font:16px system-ui;padding:16px;box-sizing:border-box;max-width:100%}label{display:block}textarea{display:block;width:100%;box-sizing:border-box;min-height:160px}`;render(){return html`<main><h1>New plugin</h1><label>Text<textarea aria-label=\"Text\"></textarea></label></main>`;}}\ncustomElements.define('plugin-view',PluginView);const root=document.getElementById('root');if(!root)throw new Error('Missing mount');root.append(document.createElement('plugin-view'));\n";
  await writeFile(resolve(root,`src/index.${framework==='react'?'tsx':'ts'}`),source);await writeFile(resolve(root,'src/style.css'),'body{margin:0;font:16px system-ui}main{padding:16px;box-sizing:border-box;max-width:100%}textarea{width:100%;box-sizing:border-box;min-height:160px}');await writeFile(resolve(root,'package.json'),JSON.stringify({name:id,version:'0.1.0',private:true,type:'module',license:'MIT',dependencies:framework==='react'?{react:'19.3.0','react-dom':'19.3.0'}:{lit:'3.3.3'}},null,2));await writeFile(resolve(root,'README.md'),'# New plugin\n\nSet the source repository to your authorized public repository. Install the pinned dependencies, then run `pwacloud build .`, `pwacloud validate .`, and `pwacloud pack package release`. Package signatures and a verification receipt are required before installation. Source preview does not grant host capabilities.\n');
}
export async function runCli(args:readonly string[]):Promise<unknown> {
  const [command,path='.',third,...rest]=args;
  if(command==='create-plugin') {if(!third) throw new PlatformError('missing-id');await createPlugin(path,third,rest[0]==='lit'?'lit':'react');return {created:resolve(path)};}
  if(command==='validate') return {valid:true,manifest:await validateDirectory(path)};
  if(command==='build') {await buildPlugin(path);return {built:resolve(path,'package')};}
  if(command==='dev') {const {startDevelopmentServer}=await import('./dev');const server=await startDevelopmentServer(path);process.once('SIGINT',()=>void server.close());process.once('SIGTERM',()=>void server.close());return {url:server.url,watch:true,trust:'Unsigned developer source only; host grants disabled'};}
  if(command==='pack') {await packDirectory(path,third??resolve(path,'../release'));return {packed:resolve(third??resolve(path,'../release')),signed:false};}
  if(command==='inspect') {const bytes=new Uint8Array(await readFile(path));const files=unpackArchive(bytes);const manifest=files['manifest.json'];if(!manifest) throw new PlatformError('missing-manifest');return {verified:false,manifest:validateManifest(parseJson(manifest)),files:Object.entries(files).map(([name,value])=>({name,bytes:value.length}))};}
  if(command==='verify') {if(!third) throw new PlatformError('missing-trust-roots');const roots=validateTrustRoots(JSON.parse(await readFile(third,'utf8')) as unknown);const names=['archive.zip','envelope.json','receipt.json','receipt.sig','envelope.sig'];const bytes=await Promise.all(names.map(name=>readFile(resolve(path,name))));const [archiveBytes,envelopeBytes,receiptBytes,signature,envelopeSignature]=bytes;if(!archiveBytes||!envelopeBytes||!receiptBytes||!signature||!envelopeSignature) throw new PlatformError('missing-package');const verified=await verifyPackage({archiveBytes,envelopeBytes,receiptBytes,signature,envelopeSignature},roots,{allowDemo:rest.includes('--allow-demo')});return {verified:true,id:verified.manifest.id,digest:verified.envelope.archive.sha256,publisher:verified.receipt.publisherIdentity};}
  if(command==='doctor') {const report:Record<string,unknown>={node:process.version,nodeSupported:Number(process.versions.node.split('.')[0])>=24,productionTrustConfigured:false,chatgpt:'Requires written authorization and human sign-in; no credentials inspected'};for(const tool of ['git','cargo']) {try {report[tool]=execFileSync(tool,['--version'],{encoding:'utf8',stdio:['ignore','pipe','ignore']}).trim();} catch {report[tool]='unavailable';}}return report;}
  if(command==='publish') {if(!third || !/^plugin-v[0-9]+\.[0-9]+\.[0-9]+(?:-[A-Za-z0-9.-]+)?$/.test(third)) throw new PlatformError('missing-reviewed-release-tag');const envelope=parseJson(new Uint8Array(await readFile(resolve(path,'envelope.json'))));if(!isEnvelope(envelope) || envelope.sourceRepository!=='https://github.com/StevenBuglione/pwacloud') throw new PlatformError('unauthorized-publish-target');const archive=new Uint8Array(await readFile(resolve(path,'archive.zip')));if(archive.length!==envelope.archive.bytes || await sha256(archive)!==envelope.archive.sha256) throw new PlatformError('digest-mismatch');unpackArchive(archive);const repository:unknown=JSON.parse(execFileSync('gh',['api','--hostname','github.com','repos/StevenBuglione/pwacloud'],{encoding:'utf8'})),commit:unknown=JSON.parse(execFileSync('gh',['api','--hostname','github.com',`repos/StevenBuglione/pwacloud/commits/${encodeURIComponent(third)}`],{encoding:'utf8'}));if(!publicRepository(repository)||!reviewedCommit(commit)||commit.sha!==envelope.sourceCommit) throw new PlatformError('publication-source-mismatch');execFileSync('gh',['workflow','run','plugin-release.yml','--repo','https://github.com/StevenBuglione/pwacloud','--ref',third],{stdio:['ignore','pipe','pipe']});return {dispatchAccepted:true,published:false,repository:envelope.sourceRepository,tag:third,sourceCommit:envelope.sourceCommit,next:'Observe the signing workflow and verify its produced release assets before reporting publication.'};}
  throw new PlatformError('unknown-command','Commands: create-plugin, validate, build, dev, pack, inspect, verify, doctor, publish');
}

