import Ajv2020 from 'ajv/dist/2020.js';
import { PlatformError } from '../../contracts/src/index';
type DependencyNode={name?:string;from?:string;version:string;path?:string;dependencies?:Record<string,DependencyNode>;devDependencies?:Record<string,DependencyNode>;optionalDependencies?:Record<string,DependencyNode>};
const schema={$id:'urn:pwacloud:dependency-tree',type:'object',required:['version'],anyOf:[{required:['name'],properties:{name:{type:'string'}}},{required:['from'],properties:{from:{type:'string'}}}],properties:{name:{type:'string',minLength:1,maxLength:240},from:{type:'string',minLength:1,maxLength:240},version:{type:'string',minLength:1,maxLength:160},path:{type:'string'},dependencies:{type:'object',additionalProperties:{$ref:'urn:pwacloud:dependency-tree'}},devDependencies:{type:'object',additionalProperties:{$ref:'urn:pwacloud:dependency-tree'}},optionalDependencies:{type:'object',additionalProperties:{$ref:'urn:pwacloud:dependency-tree'}}}};
const ajv=new Ajv2020({strict:true});ajv.addSchema(schema);const validate=ajv.compile<DependencyNode[]>({type:'array',maxItems:128,items:{$ref:schema.$id}});
type LicenseEntry={name:string;versions:string[];license?:string};
const licenseValidator=ajv.compile<Record<string,LicenseEntry[]>>({type:'object',additionalProperties:{type:'array',maxItems:8192,items:{type:'object',required:['name','versions'],properties:{name:{type:'string'},versions:{type:'array',minItems:1,items:{type:'string'}},license:{type:'string'}}}}});
type CargoMetadata={packages:{id:string;name:string;version:string;license:string|null}[];resolve:{nodes:{id:string;dependencies:string[]}[]}|null};
const object=(properties:Record<string,unknown>)=>({type:'object',required:Object.keys(properties),properties});
const cargoPackage=object({id:{type:'string'},name:{type:'string'},version:{type:'string'},license:{type:['string','null']}});
const cargoNode=object({id:{type:'string'},dependencies:{type:'array',maxItems:8192,items:{type:'string'}}});
const cargoValidator=ajv.compile<CargoMetadata>(object({packages:{type:'array',maxItems:8192,items:cargoPackage},resolve:{anyOf:[{type:'null'},object({nodes:{type:'array',maxItems:8192,items:cargoNode}})]}}));
export function licenseInventory(value:unknown):{name:string;version:string;declaredLicense:string}[] {if(!licenseValidator(value)) throw new PlatformError('invalid-license-inventory');return Object.entries(value).flatMap(([label,entries])=>entries.flatMap(entry=>entry.versions.map(version=>({name:entry.name,version,declaredLicense:entry.license??label})))).sort((a,b)=>a.name.localeCompare(b.name)||a.version.localeCompare(b.version));}
export function dependencySbom(value:unknown,licenses?:unknown,cargo?:unknown):unknown {if(!validate(value)) throw new PlatformError('invalid-dependency-tree');const declared=licenses===undefined?[]:licenseInventory(licenses);const components=new Map<string,{type:'library';name:string;version:string;purl:string;licenses?:{license:{name:string}}[]}>(),edges=new Map<string,Set<string>>();let count=0;
  function visit(node:DependencyNode,depth:number):string {if(depth>80 || ++count>100000) throw new PlatformError('dependency-tree-budget');const name=node.name??node.from;if(!name || !/^(?:@[a-z0-9._-]+\/)?[a-z0-9._-]+$/i.test(name)) throw new PlatformError('invalid-dependency-name');const purl=`pkg:npm/${name.startsWith('@')?`%40${name.slice(1)}`:name}@${encodeURIComponent(node.version)}`;components.set(purl,{type:'library',name,version:node.version,purl});const children=edges.get(purl)??new Set<string>();edges.set(purl,children);for(const dependency of Object.values({...node.dependencies,...node.devDependencies,...node.optionalDependencies})) children.add(visit(dependency,depth+1));return purl;}
  for(const node of value) visit(node,0);
  for(const component of components.values()) {const license=declared.find(d=>d.name===component.name&&d.version===component.version);if(license) component.licenses=[{license:{name:license.declaredLicense}}];}
  if(cargo!==undefined) {if(!cargoValidator(cargo)) throw new PlatformError('invalid-cargo-metadata');const ids=new Map<string,string>();for(const pkg of cargo.packages) {const purl=`pkg:cargo/${encodeURIComponent(pkg.name)}@${encodeURIComponent(pkg.version)}`;ids.set(pkg.id,purl);components.set(purl,{type:'library',name:pkg.name,version:pkg.version,purl,...(pkg.license?{licenses:[{license:{name:pkg.license}}]}:{})});}for(const node of cargo.resolve?.nodes??[]) {const id=ids.get(node.id);if(!id) throw new PlatformError('missing-cargo-component');const dependencies=new Set(node.dependencies.map(dependency=>{const target=ids.get(dependency);if(!target) throw new PlatformError('missing-cargo-component');return target;}));edges.set(id,dependencies);}}
  return {bomFormat:'CycloneDX',specVersion:'1.6',version:1,components:[...components.values()].sort((a,b)=>a.purl.localeCompare(b.purl)).map(c=>({...c,'bom-ref':c.purl})),dependencies:[...edges].sort(([a],[b])=>a.localeCompare(b)).map(([ref,dependsOn])=>({ref,dependsOn:[...dependsOn].sort()}))};
}
